# Generated by Django 6.0.3 on 2026-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_available',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto de la mascota (opcional)', null=True, upload_to='pets/'),
        ),
    ]
