# Generated by Django 6.0.3 on 2026-05-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_pet_is_available_pet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="edad",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
