# Generated by Django 6.0.3 on 2026-09-22 14:36

from django.db import migrations, models


def preserve_approved_requests(apps, schema_editor):
    AdoptionRequest = apps.get_model('core', 'AdoptionRequest')
    Pet = apps.get_model('core', 'Pet')
    approved = AdoptionRequest.objects.filter(is_approved=True)
    Pet.objects.filter(adoption_requests__in=approved).update(is_available=False)
    approved.update(status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_replace_adopter_with_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(preserve_approved_requests, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='is_approved',
        ),
    ]
